### PR TITLE
Update to netcoreapp3.1

### PR DESCRIPTION
**Pull request by tibor19**
# Module: 01
## Lab: 01

Fixes # .
.NET Core 3.0 is not supported anymore
Changes proposed in this pull request:

Update from .net 30 to .net 3.1

### CODE REVIEW

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this issue while running the course.

**Comment by VitalyMCT** [comment]
@MOC-Labs-Review  It's at https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by tibor19** [comment]
I never said it could not run. I said is not supported anymore. Please review this: https://github.com/dotnet/core/blob/main/releases.md

**Comment by JeffKoMS** [comment]
@MOC-Labs-Review Could you confirm the commit you made 23 days ago above? I'm not seeing the change in the repo and I'm also not seeing it in the most recent batch of updates? If you haven't made the commit can I assume it's all right to merge this one?

**Comment by tibor19** [comment]
I cannot make those changes. You have to merge the pull request, and delete the branch.

**Comment by JeffKoMS** [comment]
@tibor19 Yep, my previous comment was directed to @MOC-Labs-Review which is the team doing monthly testing on the labs.

**Comment by MOC-Labs-Review** [comment]
@JeffKoMS Hi Jeff, this change will be included in our February review. We will be submitting as a pull request once the review has been completed.

**Comment by MOC-Labs-Review** [comment]
This change has been submitted with pull request #396

**Pull request merged**
