### PR TITLE
Lab_5 Add missing $

### PR DESCRIPTION
**Pull request by rgozdz**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by matejetz** [comment]
this is only correct when working with the powershell on the lab machine.
when working with the cloud shell, this depends on wheter a Bash or Powershell cmd is selected. 
if Bash is selected here, the proposed version (`acrName=...`)  works while your proposal does not.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this while conducting review.

**Comment by msftnutta** [comment]
I can confirm that there is no need for this pull request as the instructions mention using Bash. I close this pull request.

**Comment by msftnutta** [comment]
I can confirm that there is no need for this pull request as the instructions mention using Bash. I close this pull request.

**Pull request closed without merging**
