### PR TITLE
Update dotnet.yml

### PR DESCRIPTION
**Pull request by tkchen7**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by msftnutta** [comment]
@tkchen7 Could you please provide some justification for this pull request? Looks to me like we are not really using the YAML for CI/CD at the moment.

**Comment by JeffKoMS** [comment]
@tkchen7 I didn't see an issue associated with this and no explanation of what this PR is addressing in the description. Can you provide the info?

**Comment by msftnutta** [comment]
Hi @JeffKoMS let's close this PR.

**Comment by msftnutta** [comment]
Since there is no additional info, ill discard the recommended changes and close this.

**Pull request closed without merging**
