### PR TITLE
Update on lab 06 : Exercise 2 -> task 1 -> Point no. 14

### PR DESCRIPTION
**Pull request by mukeshparihar**
# Module: 06
## Lab/Demo: 06

Changes proposed in this pull request:

- The packages  "Microsoft.AspNetCore.Authentication.JwtBearer and Microsoft.AspNetCore.Authentication.OpenIdConnect" has an update and the previous one is not working for the lab.

- The packages "Microsoft.Identity.Web and Microsoft.Identity.Web.UI" are working but have an update.

- Please accept the changes by accepting the pull request.

### CODE REVIEW

**Comment by msftnutta** [comment]
Hi @JeffKoMS Are we still having the upgrading work on lab 6? Will the new release of Lab 6 also fix this issue?

**Comment by JeffKoMS** [comment]
@mukeshparihar Can you please confirm if you're seeing this issue in an Azure Pass lab delivery, a cloud slice delivery,  or both.

**Comment by msftnutta** [comment]
@JeffKoMS  I tested it and this pull request helped to get rid of the warning messages during compilation. 

image

I'll merge this thanks @mukeshparihar for this pull request to suggest the minor version of NuGet packages.

**Comment by mukeshparihar** [comment]
Thank you so much.

**Pull request merged**
