### PR TITLE
Update Module 05, Lab05 Dockerfile to use .NET Core 3.1 image

### PR DESCRIPTION
**Pull request by roberthardy**
# Module: 05
## Lab/Demo: 05

Fixes: Running `dotnet new console --output . --name ipcheck` in Azure Cloud Shell as specified in the lab instructions will create a project targetting .NET Core 3.1. Currently the base image in the Dockerfile is incompatible with this version.

Changes proposed in this pull request:

- Updated the Dockerfile code in the lab 05 instructions

### CODE REVIEW

**Comment by yashints** [comment]
Your description is different to the PR's code. Also there is no 3.1-alpine for dotnet core

**Comment by seesharprun** [comment]
You can always determine the list of SDKs installed by running ``dotnet --list-sdks`` in the Cloud Shell.

**Comment by seesharprun** [comment]
While the ``mcr.microsoft.com/dotnet/core/sdk:3.1-alpine`` redirect would work, it's preferred to use either ``mcr.microsoft.com/dotnet/sdk:3.1-alpine`` or ``mcr.microsoft.com/dotnet/sdk:5.0-alpine``.

**Comment by seesharprun** [comment]
Made redundant in ee5dc87

**Pull request closed without merging**
